name: Push build changes to BlueOS
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: blueos-push-${{ github.repository }}
  cancel-in-progress: false
jobs:
  push:
    if: ${{ vars.JOSH_SYNC_ENABLED == 'true' }}
    uses: vivoblueos-lab/josh-sync/.github/workflows/blueos-push.yml@cbef7fdd806d63e75bca610c3c809a3475635ca7
    with:
      github-app-client-id: ${{ vars.JOSH_SYNC_APP_CLIENT_ID }}
      pr-author: "blueos-lab-josh-sync[bot]"
      josh-sync-repository: vivoblueos-lab/josh-sync
      josh-sync-revision: cbef7fdd806d63e75bca610c3c809a3475635ca7
    secrets:
      github-app-secret: ${{ secrets.JOSH_SYNC_APP_PRIVATE_KEY }}
      approval-user-token: ${{ secrets.JOSH_SYNC_APPROVAL_USER_TOKEN }}
